import { Link } from "react-router-dom"
import DocsLayout from "../../components/docs/layout"
import {
  DocCodeBlock,
  DocCommandRow,
  DocList,
  DocNote,
  DocP,
  DocSection,
} from "../../components/docs/primitives"
import GenericTabs from "../../components/docs/package-manager-tabs"

const headings = [
  { id: "installation", label: "Installation" },
  { id: "create-bsdk", label: "Create BSDK" },
  { id: "knowledge", label: "Knowledge (optional)" },
  { id: "chat", label: "Chat" },
]

const installTabs = [
  {
    id: "npm",
    label: "npm",
    content: <DocCommandRow command="npm install @bsdk/server" />,
  },
  {
    id: "pnpm",
    label: "pnpm",
    content: <DocCommandRow command="pnpm add @bsdk/server" />,
  },
  {
    id: "yarn",
    label: "yarn",
    content: <DocCommandRow command="yarn add @bsdk/server" />,
  },
  {
    id: "bun",
    label: "bun",
    content: <DocCommandRow command="bun add @bsdk/server" />,
  },
]

const code = "font-mono text-[13px] text-[#B8D96A]"

const BsdkServer = () => (
  <DocsLayout
    title="BSDK Server"
    tagline="Backend runtime for BSDK chat."
    headings={headings}
  >
    <DocSection id="installation" title="Installation">
      <GenericTabs tabs={installTabs} />
    </DocSection>

    <DocSection id="create-bsdk" title="Create BSDK">
      <DocP>
        First run <code className={code}>npx @bsdk/cli init</code> from your
        backend root to generate provider and knowledge files under{" "}
        <code className={code}>./bsdk/</code>:
      </DocP>
      <DocCodeBlock
        snippet={`./bsdk
├── providers.ts        ← AI providers (groq, openai, etc.)
└── KnowledgeConfig.ts  ← knowledge credentials (Pinecone, Cohere)`}
      />
      <DocP>
        Then import the generated provider and create the runtime:
      </DocP>
      <DocCodeBlock
        snippet={`import { createBSDK } from "@bsdk/server";
import { groq } from "./bsdk/providers";

const bsdk = createBSDK({
  model: groq("openai/gpt-oss-120b"),
});`}
      />
      <DocList
        items={[
          <>
            <code className={code}>model</code> — pass a provider helper (e.g.{" "}
            <code className={code}>groq</code>) and the model string (e.g.{" "}
            <code className={code}>openai/gpt-oss-120b</code>).
          </>,
        ]}
      />
      <DocP>
        For provider configuration, see{" "}
        <Link to="/docs/providers" className="text-[#B8D96A] underline-offset-4 hover:underline">AI Providers</Link>.
      </DocP>
    </DocSection>

    <DocSection id="knowledge" title="Knowledge (optional)">
      <DocP>
        To enable document-based Knowledge, pass the generated knowledge config into the runtime:
      </DocP>
      <DocCodeBlock
        snippet={`import { createBSDK } from "@bsdk/server";
import { groq } from "./bsdk/providers";
import { knowledgeConfig } from "./bsdk/KnowledgeConfig";

const bsdk = createBSDK({
  model: groq("openai/gpt-oss-120b"),

  knowledge: {
    pinecone: knowledgeConfig.pinecone,
    cohere: knowledgeConfig.cohere,
  },
});`}
      />
      <DocNote>
        <code className={code}>KnowledgeConfig.ts</code> is generated by{" "}
        <code className={code}>npx @bsdk/cli init</code> and reads from{" "}
        <code className={code}>PINECONE_API_KEY</code>,{" "}
        <code className={code}>PINECONE_INDEX_HOST</code>, and{" "}
        <code className={code}>COHERE_API_KEY</code> in your{" "}
        <code className={code}>.env</code> file.
      </DocNote>
      <DocP>
        For the full knowledge setup, see{" "}
        <Link to="/docs/knowledge-setup" className="text-[#B8D96A] underline-offset-4 hover:underline">Knowledge</Link>.
      </DocP>
    </DocSection>

    <DocSection id="chat" title="Chat">
      <DocP>
        The runtime exposes <code className={code}>bsdk.chat(messages, botId, description)</code>,
        which returns a streaming HTTP response. Forward it from a backend route:
      </DocP>
      <DocCodeBlock
        snippet={`app.post("/api/chat", async (req, res) => {
  const { messages, botId, description } = req.body;

  const response = await bsdk.chat(messages, botId.toString(), description);

  res.status(response.status);
  response.headers.forEach((value, key) => {
    res.setHeader(key, value);
  });

  if (!response.body) {
    return res.end();
  }

  const reader = response.body.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    res.write(Buffer.from(value));
  }

  res.end();
});`}
      />
    </DocSection>
  </DocsLayout>
)

export default BsdkServer
